#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         0
bspc config borderless_monocle   false

bspc config window_gap            10
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config top_padding            $(( 45 + 27+8 + 13  +  1 ))
bspc config left_padding           $(( 10  +  60 ))
bspc config right_padding          $(( 10  +  60 ))
bspc config bottom_padding         $(( 45  +  10 ))

# autostart up applications 
~/.config/polybar/launch.sh &
picom & 
feh --bg-fill ~/Pictures/wal/sniper-2.jpg &
xrdb merge ~/.Xresources &
sxhkd 
