#! /bin/sh

PRODUCTIVE_MODE OFF

# super + r to reload bspwmrc

sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十


bspc config border_width 0        
bspc config window_gap             20

bspc config top_padding            $(( 12 + 27+8 + 13  +  1 ))
bspc config left_padding           $(( 30  +  60 ))
bspc config right_padding          $(( 30  +  60 ))
bspc config bottom_padding         $(( 20  +  10 ))

#bspc config top_padding            $(( 12 + 27+8 + 13  +  35+15))
#bspc config left_padding           $(( 30  +  105+45 ))
#bspc config right_padding          $(( 30  +  105+45 ))
#bspc config bottom_padding         $(( 20  +  35+15 ))


bspc config split_ratio            0.5
bspc config borderless_monocle     false
bspc config gapless_monocle        false

bspc config focus_follows_pointer  true
#bspc config click_to_focus any

bspc config presel_feedback_color  "#666666"
bspc config normal_border_color    "#333333"
bspc config focused_border_color   "#555555"

bspc rule -a URxvt:URxvtFloat state=floating
bspc rule -a URxvt:URxvt-dmesg desktop='^10'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a imv state=floating
bspc rule -a Spicy state=FLOATING
bspc rule -a qemu-system-x86_64 state=floating
bspc rule -a feh:feh state=floating
bspc rule -a feh:fehwrap-fs state=fullscreen

# Autorun stuff
$HOME/.config/polybar/launch.sh
urxvtc -name URxvt-dmesg -e dmesg -w

